### ISSUE TITLE
Unable to download .zip file because it "needs authorization"

### ISSUE THREAD

**Issue by scepterdoescode** [pedrommcarrasco/Brooklyn#106]
## Required information
- Mac model: MacBook Pro (13-inch, M1, 2020)
- macOS version: Monterey 12.2.1

## Description of issue
I'm curious enough to download this screensaver. The problem was that I was unable to download it on Chrome because it "needs authorization." How can I bypass this issue?

**Comment by pedrommcarrasco** [comment]
Look into this project's [README.md](https://github.com/pedrommcarrasco/Brooklyn#manual-hand), it probably has the answer for you.
