### ISSUE TITLE
Option to allow animation to run longer

### ISSUE THREAD

**Issue by amiantos** [pedrommcarrasco/Brooklyn#12]
### Is your feature request related to a problem? Please describe.
I think the animations cycle a bit too fast, creating kind of a strobe effect that feels distracting to have on my screen in the office.

###  Describe the solution you'd like
It would be great if the screensaver was configurable to allow variable lengths of time before the animation is replaced.

**Comment by pedrommcarrasco** [comment]
For now that's impossible @amiantos 😢
But once I finish doing https://github.com/pedrommcarrasco/Brooklyn/issues/3 this could be a good setting to implement in https://github.com/pedrommcarrasco/Brooklyn/issues/4

I'm going to close this issue for now, and if you can, please comment this in https://github.com/pedrommcarrasco/Brooklyn/issues/4 so we can have the preferences options centralised in the same place
