### ISSUE TITLE
Not workin in 10.11.6

### ISSUE THREAD

**Issue by avv3lenato** [pedrommcarrasco/Brooklyn#16]
Not workin in MacOS El Capitan 10.11.6
iMac Retina 4K, 21.5 late 2015
Screenshot attached:
<img width="696" alt="schermata 2019-01-02 alle 11 18 00" src="https://user-images.githubusercontent.com/46316172/50587943-31771000-0e80-11e9-9b72-02ff8d62627e.png">

“You cannot use the SavingYourScreen screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver.”

**Comment by pedrommcarrasco** [comment]
Hey @ avv3lenato, sorry but just saw this now.
Take a look at this https://github.com/pedrommcarrasco/Brooklyn/issues/10 and see if it helps

> * It's suggested that you download the file with Safari)
> * And try everything with settings Closed from the start

**Comment by LiWenChi** [comment]
I have the same problem in 10.13.3
![1550550901806](https://user-images.githubusercontent.com/26902075/52990368-dd7db600-3442-11e9-8336-9b66556fd797.jpg)

**Comment by pedrommcarrasco** [comment]
Hey @LiWenChi, did you try what I said? macOS can be a bit tricky with screen savers written in Swift

**Comment by sbgraphic** [comment]
Hello, same issue here wiht 10.11.6 (old hardware, Mac Pro 3,1)
 download again in zip and installed manually in ~/Library/Screen  Savers
Still does not diplay except incompatible warning…
Best

**Comment by pedrommcarrasco** [comment]
Hey @sbgraphic, 
I'm afraid I'm not able to validate and test your scenario but try doing it a few times and make sure you do everything with preferences closed.

**Comment by Limman** [comment]
The same problem. 
OS X 10.11.6, downloaded via Firefox.

**Comment by pedrommcarrasco** [comment]
I'm not sure if this is a pattern with 10.11.6 but as always try the following @Limman:
* It's suggested that you download the file with Safari
* And try everything with Preferences **closed** from the start

**Comment by sbgraphic** [comment]
Hello, well nope, I did that already several times (safari download anyway) … same issue, tried to install in one user only ~/Library/Screen Savers or all users /Library/Screen Savers, same result… I haven't restart the Mac yet, will try later. Thanks !

**Comment by pedrommcarrasco** [comment]
It's sorry to say but I'm powerless here 😢
macOS can be a pain with screen savers built with Swift and I don't have ways of testing it for every version. I have reports of people having it working with 10.11.6 so I would say it's probably macOS not playing along 😞

**Comment by sbgraphic** [comment]
No worries I'll wait till I upgrade my hardware… then my macOS, hopefully soon ! :-)

**Comment by LiWenChi** [comment]
> Hey @LiWenChi, did you try what I said? macOS can be a bit tricky with screen savers written in Swift. Also try seeing the preview. Sometimes, the thumbnail doesn't load before opening the fullscreen preview

@pedrommcarrasco  Excuse me, I didn't try it at first. It can be used now, thank you. Great! ! !
