### ISSUE TITLE
macOS 10.13.6 not working

### ISSUE THREAD

**Issue by eloyaldea** [pedrommcarrasco/Brooklyn#17]
#### General troubleshooting

Before logging an issue please verify that:
- [x] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [x] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 13" Late 2011
- [x] macOS version: 10.13.6 (17G5014)

#### Description of issue

{{ What's happening? }}

'Can't use the screensaver Brooklyn with this macOS version. Please contact with the provider to obtain a more recent version of this screen saver'

**Comment by pedrommcarrasco** [comment]
Hey @eloyaldea, sorry but just saw this now.
Take a look at this https://github.com/pedrommcarrasco/Brooklyn/issues/10 and see if it helps

> * It's suggested that you download the file with Safari)
> * And try everything with settings Closed from the start

**Comment by eloyaldea** [comment]
Managed to install it after closing settings and trying (installing / uninstalling) a couple times and it worked. It worked but it was kind of buggy, the screensaver itself works fine, just the installation. I downloaded using safari.

**Comment by pedrommcarrasco** [comment]
Yeah, not my fault at all tho. That's a common problem across screensavers built with swift. We hope swift 5 solves some of these problems.

**Comment by climbingDog** [comment]
mac os 10.14.4 ,not working too,however the installation is ok.

**Comment by pedrommcarrasco** [comment]
It is working here @climbingDog.
Try re-installing and following the steps mentioned above
