### ISSUE TITLE
4K/5K Support

### ISSUE THREAD

**Issue by seanhoyt** [pedrommcarrasco/Brooklyn#19]
While it looks great on my 4K iMac, it doesn't seem to be running at the native resolution (looks much sharper on the 1080p external display I have).

**Comment by pedrommcarrasco** [comment]
I wish I could support higher resolutions but Apple's original source is 1080p, as far as I know, I can't easily upscale it to 4k/5k. Still, thanks for your input @seanhoyt

**Comment by fr0der1c** [comment]
@pedrommcarrasco I didn't watch the Apple Special Event. Are **all** the animations from Apple? It doesn't look good on my iMac 5K. I wonder if we could at least upscale **some** of the animations to greater resolutions.

**Comment by pedrommcarrasco** [comment]
yes @fr0der1c, every single animation is from Apple, problem is, they released them in 1080p

**Comment by simplenotezy** [comment]
@pedrommcarrasco Let's dig into this! Perhaps we may get an Apple Insider to poke the right guy and have them export it in 5k for us? Would be so cool!

**Comment by simplenotezy** [comment]
Let's leave the issue open until we've found a solution. Hopefully we can. Help me spread the word 😊 https://twitter.com/simplenotezy/status/1306484910425767943?s=20

**Comment by simplenotezy** [comment]
No luck so far. @pedrommcarrasco got any idea how we could get the 4k versions? It must be possible, even though it's not just laying around on the internet.

**Comment by pedrommcarrasco** [comment]
You can try to create the 4k version based on AI. Here's a user sharing how:
https://github.com/pedrommcarrasco/Brooklyn/issues/50#issuecomment-718940923
