### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by codylegger** [pedrommcarrasco/Brooklyn#20]
Sometime down the road do you think you can add the ability to slow the animations down? Since its a screensaver and going to be displayed for long periods of times it kind of goes too fast. But still love what you have so far!

**Comment by pedrommcarrasco** [comment]
Hey @codylegger 👋 
Thanks for you input but I think I won't ever be able to "slowdown" it properly. What I'll be working on and kind of solves your problem is being able to select which animations you want to display and for how much time.

**Comment by janaagaard75** [comment]
Came here to add the same suggestion. Figured out that the animations are mp4 files, making it difficult to adjust the speed. Tried slowing one of the videos down with ezgif.com. Here's the result. (Hope the link works.)

https://drive.google.com/file/d/1gSwODdhr1IeqJShFBW2tm54gYwIKQv7S/view?usp=sharing

**Comment by pedrommcarrasco** [comment]
Thanks for you effort @janaagaard75! 
In my opinion it doesn't look very good since it doesn't have the required frames per second but it's something we can see in the future 😄

**Comment by janaagaard75** [comment]
I completely agree that the choppiness of the animation isn't acceptable. 🙂

**Comment by BruceInLouisville** [comment]
Came to leave same comment. On my MB Pro (mid-2014), they seem frenetic, even the ones that I suspect should be less so.

If it's not possible, it's not possible -- but it would enhance the saver to be able to slow them down some. Or, at least slow some of them down.

Thanks for the work to put this together!
