### ISSUE TITLE
Not signed

### ISSUE THREAD

**Issue by ygini** [pedrommcarrasco/Brooklyn#22]
A Gatekeeper Developer ID is free, please, get one and properly sign and sandbox your app

https://developer.apple.com/developer-id/

**Comment by pedrommcarrasco** [comment]
This was developed for fun so I didn't took the time needed to do that @ygini 
When a new release comes out (probably with a preferences menu) I'll also add that :)

**Comment by ygini** [comment]
Thanks!

**Comment by sniesel** [comment]
Sounds awesome, thank you @pedrommcarrasco for the work.

**Comment by pedrommcarrasco** [comment]
After playing around I'm not sure if I'm apple to sandbox a screensaver. I'm able to sandbox applications via the capabilities menu but that doesn't show up for screen savers 🤔

**Comment by ygini** [comment]
Did you tried to sign it via the command line?

**Comment by pedrommcarrasco** [comment]
I'm able to sign it, just not able to activate the sandbox capability
