### ISSUE TITLE
Brooklyn 2.0.0

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/Brooklyn#28]
Version 2.0.0 is now on pre-release. Download it [here](
https://github.com/pedrommcarrasco/Brooklyn/releases/download/2.0.0/Brooklyn.saver.zip).
If you find an issue related to this version please write it here.

### What's new?
* Adds a new preferences menu that allows you to select which animations you want to see, how many times they should loop and randomize its order.
* Signed Brooklyn
* Bumped minimum macOS version from 10.9 to 10.11.

### Issues
* Signed `.saver` - #22 
* Isolated animations - #3 
* Added preferences menu - #4, #12, #20, #23 

#### Related People
Thanks to @nsmyself, @peusebio, @kjhx, @MattSHallatt, @amiantos, @vipuldelwadia, @codylegger, @janaagaard75, @Leslie-Luo & @ygini. You were all involved in reporting, suggesting or contributing to this version, if possible please download it & provide feedback.

**Comment by amiantos** [comment]
That download link is _slow_. Took about 20 minutes to download. Just a heads up...

This is great! Don't want to get into my notes without saying that up front, this is already a big improvement on the usability of this as an actual screensaver, so total kudos! Interface is clean as well, feels Apple-y :)

I'm not sure how in-depth you want the feedback to be, but here are some initial notes based on playing around for a minute...

- Having the loop preview show over the screensaver options makes it seem like the loop/order options are related to the animation you're previewing, this kinda confused me at first thinking I could select the number of loops for that specific animation. Maybe the preview should be over the animation list? Or under it? Or maybe something else can be done to make sure it's clear that those two settings are "screensaver level" and not "animation level". I don't have a great suggestion here off the top of my head.

- Maybe 'Original' should be renamed to something like "All Animations (Apple Version)" or something similar to indicate that if you have that one selected you don't need the others. Or, this might be better, ditch "Original" and have all loops selected by default, with 1 loop or whatever they are in the original animation.

- In regard to selecting loops, a "Select/Deselect All" option would be cool, though the second part of the above idea (all loops selected by default) would get rid of the need for this. I also found myself trying to use the spacebar and arrow keys to quickly toggle loops on and off, pretty edge-case-y though.

- This is kind of splitting hairs, but I found the naming of "Number of Loops" to be slightly confusing at first. Some part of me sees "Number of Loops: 0" and thinks "This won't be played", and sees "Number of Loops: 1" as "This will be played once". Not sure how others feel about this. Electric Sheep uses "Repeat Loops: [ 2 ] Times" as their naming and defaults, which makes it a little clearer maybe. I'd maybe lean toward "Repeat Animations: [ 2 ] Times".

**Comment by pedrommcarrasco** [comment]
That's some great feedback @amiantos!

> That download link is slow. Took about 20 minutes to download. Just a heads up...

Brooklyn's size in this new version is around 200mb (2x the original size), so that might explain.

> Having the loop preview show over the screensaver options makes it seem like the loop/order options are related to the animation you're previewing, this kinda confused me at first thinking I could select the number of loops for that specific animation. Maybe the preview should be over the animation list? Or under it? Or maybe something else can be done to make sure it's clear that those two settings are "screensaver level" and not "animation level". I don't have a great suggestion here off the top of my head.

I'm thinking of adding a separator, just like there's one separating media and reports 

> Maybe 'Original' should be renamed to something like "All Animations (Apple Version)" or something similar to indicate that if you have that one selected you don't need the others. Or, this might be better, ditch "Original" and have all loops selected by default, with 1 loop or whatever they are in the original animation

While ditching is an interesting idea, the main problem is that every single animation isn't edited and cu in the exact same way the original is. They were edited & extended so having a specific option to show the original material is **important** in my opinion. Renaming it to `All Animations (Apple Version)` looks good to me 😄

> In regard to selecting loops, a "Select/Deselect All" option would be cool, though the second part of the above idea (all loops selected by default) would get rid of the need for this.

Will add this 👍 

>  I also found myself trying to use the spacebar and arrow keys to quickly toggle loops on and off, pretty edge-case-y though.

 Wonderful idea ✨ 

> This is kind of splitting hairs, but I found the naming of "Number of Loops" to be slightly confusing at first. Some part of me sees "Number of Loops: 0" and thinks "This won't be played", and sees "Number of Loops: 1" as "This will be played once". Not sure how others feel about this. Electric Sheep uses "Repeat Loops: [ 2 ] Times" as their naming and defaults, which makes it a little clearer maybe. I'd maybe lean toward "Repeat Animations: [ 2 ] Times".

This is truly hard indeed. But "Repeat animations: 0 Times" sounds clearer than "Number of Loops: 0" 👍

**Comment by ygini** [comment]
Hi

Thanks a for the new version (and I confirm that the DL link is so slow).

Regarding the code signature, I still get the unidentified developer alert, even if I see your signature in the bundle, I will check this in depth, they will maybe lead to a bugreport for Apple.

As Brad, I think a select/deselect all option is mandatory. I recommend to use the macOS usual behavior for this: option click to do the action for all (like when you enable Remote Management feature on macOS, option click when you select remote management right to fo the action on all).

On the same topic, we can use the up/down arrows to change the line, but we can’t use the space to select/unselect the checkbox.

Still on the same topic, provide a documentation to manage the preferences with a MDM and use proper API from UserDefautls to check if a settings is managed or not (and if so, disable the settings UI).

As Brad, I do not get the Loop settings at first.

Thanks a lot for your work!

**Comment by pedrommcarrasco** [comment]
> Regarding the code signature, I still get the unidentified developer alert, even if I see your signature in the bundle, I will check this in depth, they will maybe lead to a bugreport for Apple.

Let me know if you find something 🤔 

> Still on the same topic, provide a documentation to manage the preferences with a MDM and use proper API from UserDefautls to check if a settings is managed or not (and if so, disable the settings UI).

While this would be cool it's a bit out of scope for this release. Will dive into it later

Thanks so much for sharing your @ygini 🙇

**Comment by pedrommcarrasco** [comment]
What if instead of buttons (select/deselect all), you were able to CMD+A (select all) then press space to toggle every one? @amiantos @ygini

**Comment by iDjay** [comment]
Maybe turn off the click sound when closing preferences. I got confused the first times 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
@pedrommcarrasco where can I download the current version? It's a bit confusing now.

**Comment by amiantos** [comment]
I'm still getting the "unidentified developer" warning on that new link.

I like the CMD+A + Space trick.

Lookin' good!

**Comment by pedrommcarrasco** [comment]
That's weird because when running `codesign --verify --verbose=4` it says:
```
Brooklyn.saver/: valid on disk
Brooklyn.saver/: satisfies its Designated Requirement
```

Plus, `codesign -dvvv Brooklyn.saver/Contents/MacOS/Brooklyn` results in
```
...
Authority=Mac Developer: pedrocarrasco95@icloud.com (C5VN68CN88)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
...
```

**Comment by pedrommcarrasco** [comment]
can you try these two commands and see if you get the same results @amiantos?

**Comment by stevemoser** [comment]
@pedrommcarrasco I see the same thing you do with the two commands and it shows a `Verifying Brooklyn.saver` loading modal but it still shows 'unidentified developer' when it finishes. Also the random order feature doesn't seem to work for me.

**Comment by stevemoser** [comment]
@pedrommcarrasco The random order feature works if I select any item but All Animations. Also using space to check a checkbox quickly toggles and untoggles it.

**Comment by pedrommcarrasco** [comment]
Yes "All Animations" (Apple's Version) is a single video without edit from Apple's event. You can't randomize that. What you can randomize is the order of the selected items. And yes, spacebar is a shortcut to toggle the select animation @stevemoser

**Comment by pedrommcarrasco** [comment]
Going to change random text from "Random Order" to "Play selected items in a random order"

**Comment by stevemoser** [comment]
@pedrommcarrasco Thats way better. Or even disable it if only one is selected to prevent it from feeling broken for those that don't read every haha. And the spacebar thing is an issue not a note. It toggles on key up AND key down leaving the checkbox in its original state.

**Comment by stevemoser** [comment]
@pedrommcarrasco Actually I just want an easy button. I want to randomize all of them. I'm lazy, make the computer do it 😛

**Comment by pedrommcarrasco** [comment]
You can CMD+A & Space to select all of them 😄
Trying to keep things clean without having tons of buttons around 🤔

**Comment by pedrommcarrasco** [comment]
Regarding your issue with the spacebar, I'm not able to reproduce it but it should only trigger on key up

**Comment by ygini** [comment]
I've checked the signature on my side, it seems to be done correctly, but not recognized by the system. If you've spare one, you can use a Developer Technical Support ticket to ask Apple directly to look on your product and tell why it's not working.

If for some reasons it's linked to a bug on Gatekeeper, they may recredit the DTS.

**Comment by pedrommcarrasco** [comment]
Could it be because it's a free account? I mean, I haven't paid this year's subscription 🤔

**Comment by ygini** [comment]
No, free account is the right option to get Developer ID to sign non App Store distribution software (but you won’t have DTS available with a free account). You need a paid one only for App Store.

**Comment by pedrommcarrasco** [comment]
I'm asking because according to https://developer.apple.com/programs/whats-included/

> Developer ID for macOS
You can distribute your Mac applications outside of the Mac App Store by using Developer ID. Signing your Mac applications, plug-ins, and installer packages with a Developer ID certificate lets Gatekeeper verify that apps are not created by malware developers and haven't been tampered with since they were signed

**Comment by ygini** [comment]
Indeed the doc is weird, but it was always supposed to be free (otherwise no one would have used it). 

Try to renew your cert from Xcode and see if you properly get a new one. That should be a proper test.

**Comment by pedrommcarrasco** [comment]
I'm not able to renew certificates with a free account (from the portal). Deleting or attempting to create a new one will fail

**Comment by pedrommcarrasco** [comment]
Soo, after talking with John (creator of https://github.com/JohnCoates/Aerial) it seems that the solution is an enrolled account. I'm going to buy a subscription sooner or later when I release an iOS application I've been working on so it's a matter of time until this gets truly fixed. For now, let's leave it as it is.

**Comment by pedrommcarrasco** [comment]
I'm releasing 2.0.0 in its current state. We have everything pretty much done and we need more people using it to gather more data and discover new bugs. In the meantime, I'm also going to take a break from Brooklyn for a while - will just fix any bug that shows up.

Thanks to everyone involved ❤️

**Comment by codylegger** [comment]
Sorry for coming in late to the party, but was wondering maybe if you could
add a selectable delay in between the next animation so its not so flashy.
and looks more like a screen saver. I know you can't slow the animation
down, but I think that would help. Thanks for the hard work though, I think
your doing a great job. Missed out on the earlier updates, but the latest
seems to be working just fine for me. Did get the untrusted dev
notification, but that's okay.

Thanks again!

**Comment by pedrommcarrasco** [comment]
That could be something that I could do in the future. Thanks @codylegger
