### ISSUE TITLE
Animations List (Naming & Edit/Isolate)

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/Brooklyn#3]
Isolate & edit every possible animation in order to use them in #4 

Bellow, there's a list with every animation that should be isolated. If you want to isolate one and suggest a name, please reply on this issue.

# Current Progress: 35 from 77

## ❌   1
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 33" src="https://user-images.githubusercontent.com/26525777/53288299-c4487280-377e-11e9-9828-1823b6006dd5.png">

## ✅ 2
Name - **Hills** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 19 53" src="https://user-images.githubusercontent.com/26525777/53288300-c4487280-377e-11e9-8462-0241b9437e80.png">

## ❌  3
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 38" src="https://user-images.githubusercontent.com/26525777/53288301-c4487280-377e-11e9-8846-a0e3829d5b31.png">

## ❌  4
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 03" src="https://user-images.githubusercontent.com/26525777/53288302-c4487280-377e-11e9-9923-b9dabdecdd20.png">

## ✅ 5
Name - **Gummy Worms** (suggested by @peusebio)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 19 14" src="https://user-images.githubusercontent.com/26525777/53288303-c4487280-377e-11e9-95be-5b23a4240181.png">

## ❌ 6
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 19 11" src="https://user-images.githubusercontent.com/26525777/53288304-c4487280-377e-11e9-92e4-d796f0479bfa.png">

## ❌  7
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 18 38" src="https://user-images.githubusercontent.com/26525777/53288305-c4e10900-377e-11e9-9244-6e819236a10d.png">

## ❌  8
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 18 35" src="https://user-images.githubusercontent.com/26525777/53288307-c4e10900-377e-11e9-9162-8490af262c51.png">

## ❌  9
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 42" src="https://user-images.githubusercontent.com/26525777/53288309-c4e10900-377e-11e9-9117-72435e249da8.png">

## ✅ 10  
Name -  **Running in Grass**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 20 07" src="https://user-images.githubusercontent.com/26525777/53288310-c4e10900-377e-11e9-8569-9fa9024f6c43.png">

## ❌  11
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 19 18" src="https://user-images.githubusercontent.com/26525777/53288311-c4e10900-377e-11e9-9e80-d73cbe82256a.png">

## ❌  12
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 18 45" src="https://user-images.githubusercontent.com/26525777/53288312-c5799f80-377e-11e9-8c70-a0551fccfe7d.png">

## ✅ 13
Name - **Geometric Shapes** (suggested by @peusebio)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 18 08" src="https://user-images.githubusercontent.com/26525777/53288313-c5799f80-377e-11e9-9992-58390ec0c74d.png">

## ❌  14
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 58" src="https://user-images.githubusercontent.com/26525777/53288314-c5799f80-377e-11e9-97c2-0c1463b6aa7d.png">

## ❌  15
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 54" src="https://user-images.githubusercontent.com/26525777/53288315-c5799f80-377e-11e9-94ac-e3eab13825ef.png">

## ❌  16
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 26" src="https://user-images.githubusercontent.com/26525777/53288316-c5799f80-377e-11e9-96b6-4df8a24d1341.png">

## ❌  17
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 22" src="https://user-images.githubusercontent.com/26525777/53288317-c5799f80-377e-11e9-80d6-f972b376b50f.png">

## ❌  18
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 17" src="https://user-images.githubusercontent.com/26525777/53288318-c6123600-377e-11e9-9cc6-c4edc94fb0e7.png">

## ❌  19
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 48" src="https://user-images.githubusercontent.com/26525777/53288319-c6123600-377e-11e9-91fb-3ae362afdc3d.png">

## ❌  20
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 11" src="https://user-images.githubusercontent.com/26525777/53288320-c6123600-377e-11e9-9ec2-b60673c06452.png">

## ❌  21
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 19 23" src="https://user-images.githubusercontent.com/26525777/53288321-c6123600-377e-11e9-845e-b41f08de69b9.png">

## ❌  22
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 18 50" src="https://user-images.githubusercontent.com/26525777/53288322-c6123600-377e-11e9-961a-3a8b5c2578fa.png">

## ❌  23
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 18 12" src="https://user-images.githubusercontent.com/26525777/53288323-c6aacc80-377e-11e9-95f6-2806d0c55be4.png">

## ❌  24
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 31" src="https://user-images.githubusercontent.com/26525777/53288324-c6aacc80-377e-11e9-92b2-34765247161d.png">

## 🚧 25
Name - **Noise Stripes**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 59" src="https://user-images.githubusercontent.com/26525777/53288325-c6aacc80-377e-11e9-89e7-62361e92bb51.png">

## ✅ 26
Name -**Play-Doh** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 55" src="https://user-images.githubusercontent.com/26525777/53288326-c6aacc80-377e-11e9-89ea-2b37ed9b7c14.png">

## ✅ 27
Name - **Layers** (suggested by @peusebio)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 51" src="https://user-images.githubusercontent.com/26525777/53288327-c6aacc80-377e-11e9-8d75-da37c0578708.png">

## ❌  28
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 16 45" src="https://user-images.githubusercontent.com/26525777/53288328-c7436300-377e-11e9-8d4e-89e18d1d2323.png">

## ✅ 29
Name - **Yolk**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 18" src="https://user-images.githubusercontent.com/26525777/53288329-c7436300-377e-11e9-8c18-0a7334c7ef54.png">

## ✅ 30
Name - **Splash**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 12" src="https://user-images.githubusercontent.com/26525777/53288330-c7436300-377e-11e9-938a-44bc586d3ed3.png">

## ✅ 31
Name -**Ball Pit**
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 05" src="https://user-images.githubusercontent.com/26525777/53288331-c7436300-377e-11e9-9e76-60395015008b.png">

## ✅  32
Name - **Wet**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 00" src="https://user-images.githubusercontent.com/26525777/53288332-c7dbf980-377e-11e9-8c96-96657ef29013.png">

## ❌  33
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 54" src="https://user-images.githubusercontent.com/26525777/53288333-c7dbf980-377e-11e9-8faa-c7e68c120e0a.png">

## ❌  34
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 17" src="https://user-images.githubusercontent.com/26525777/53288334-c7dbf980-377e-11e9-853d-8ca67d92d4a1.png">

## ✅ 35
Name - **Iris** (suggested by @peusebio)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 19 39" src="https://user-images.githubusercontent.com/26525777/53288335-c7dbf980-377e-11e9-919b-05153964144a.png">

## ✅ 36
Name - **Shelves** (suggested by @NSMyself )
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 18 55" src="https://user-images.githubusercontent.com/26525777/53288336-c7dbf980-377e-11e9-9ab2-b9954912433f.png">

## ❌  37
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 18 22" src="https://user-images.githubusercontent.com/26525777/53288337-c8749000-377e-11e9-9c51-ef5cd4d289b6.png">

## ✅ 38
Name - **Volumetric** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 17 34" src="https://user-images.githubusercontent.com/26525777/53288338-c8749000-377e-11e9-8fa5-b78b062015b8.png">

## ❌  39
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 17 04" src="https://user-images.githubusercontent.com/26525777/53288339-c8749000-377e-11e9-9a0a-e39362023e5c.png">

## ✅ 40
Name - **Zebra** (suggested by @peusebio)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 24" src="https://user-images.githubusercontent.com/26525777/53288340-c8749000-377e-11e9-9688-7e6b5938f0a0.png">

## 💀 41
Couldn't create anything good

<img width="1680" alt="screenshot 2019-02-23 at 15 15 44" src="https://user-images.githubusercontent.com/26525777/53288341-c8749000-377e-11e9-8b5c-c16c8eb30e2a.png">

## ✅ 42
Name - **Picasso** (suggested by @peusebio)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 41" src="https://user-images.githubusercontent.com/26525777/53288342-c90d2680-377e-11e9-830b-fed008b4046c.png">

##  🚧 43
Name - _Undefined_
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 36" src="https://user-images.githubusercontent.com/26525777/53288343-c90d2680-377e-11e9-8b3a-8aba9f1ebc60.png">

## ✅ 44
Name - **Avatar Tissue**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 30" src="https://user-images.githubusercontent.com/26525777/53288344-c90d2680-377e-11e9-83dc-9ad2ceeae066.png">

## ✅ 45
Name - **Magnify**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 24" src="https://user-images.githubusercontent.com/26525777/53288345-c90d2680-377e-11e9-9afc-643ad6a62259.png">

## ❌  46
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 21 03" src="https://user-images.githubusercontent.com/26525777/53288346-c90d2680-377e-11e9-9c91-60925daf5c44.png">

## ❌  47
Name - _Undefined_
👨‍💻-  _Undefined_

<img width="1680" alt="screenshot 2019-02-23 at 15 20 21" src="https://user-images.githubusercontent.com/26525777/53288347-c90d2680-377e-11e9-8f95-c961791a907b.png">

## ✅ 48
Name - **Shards** (suggested by @NSMyself)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 19 44" src="https://user-images.githubusercontent.com/26525777/53288348-c9a5bd00-377e-11e9-85a5-c25619138da4.png">

## 🚧 49
Name - **Color Path**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 18 59" src="https://user-images.githubusercontent.com/26525777/53288349-c9a5bd00-377e-11e9-8d20-28f06ca00712.png">

## 🚧 50
Name - **Blue Sand**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 18 26" src="https://user-images.githubusercontent.com/26525777/53288350-c9a5bd00-377e-11e9-9125-eb9e9dc837ca.png">

## ✅ 51
Name - **Leaf** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 17 38" src="https://user-images.githubusercontent.com/26525777/53288351-c9a5bd00-377e-11e9-8986-ec63f8f285b0.png">

## 🚧 52
Name - **Snakes**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 17 08" src="https://user-images.githubusercontent.com/26525777/53288352-c9a5bd00-377e-11e9-8ec1-25af7b391534.png">

## ✅ 53
Name - **Sound Spectrum**
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 34" src="https://user-images.githubusercontent.com/26525777/53288353-c9a5bd00-377e-11e9-9524-c1b9e3743b62.png">

##  💀 54
Couldn't create anything good.

<img width="1680" alt="screenshot 2019-02-23 at 15 15 48" src="https://user-images.githubusercontent.com/26525777/53288354-ca3e5380-377e-11e9-8b6d-0a38783431e9.png">

## ✅ 55
Name - **Surface Water**
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 15" src="https://user-images.githubusercontent.com/26525777/53288355-ca3e5380-377e-11e9-8247-06b2f87ad312.png">

## ✅ 56
Name - **Glow** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 08" src="https://user-images.githubusercontent.com/26525777/53288356-ca3e5380-377e-11e9-8551-8ac2c0394b56.png">

## ✅ 57
Name - **River Noir**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 04" src="https://user-images.githubusercontent.com/26525777/53288357-ca3e5380-377e-11e9-807e-bb39fe4edf0d.png">

## ✅ 58
Name - **Fangs**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 14 58" src="https://user-images.githubusercontent.com/26525777/53288358-ca3e5380-377e-11e9-8d17-cc361aaa7d4e.png">

## ✅ 59
Name - **Defragmentation** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 14 48" src="https://user-images.githubusercontent.com/26525777/53288359-cad6ea00-377e-11e9-95e9-e2d603ed6c0f.png">

## ✅ 60
Name - **Moisty Colors**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 14 37" src="https://user-images.githubusercontent.com/26525777/53288360-cad6ea00-377e-11e9-8576-2b89459f26d7.png">

## 🚧   61
Name - **Doodle**
👨‍💻- @kjhx

<img width="1680" alt="screenshot 2019-02-23 at 15 14 29" src="https://user-images.githubusercontent.com/26525777/53288361-cad6ea00-377e-11e9-8ec0-d726d389a39d.png">

## ✅ 62
Name - **Trapezium**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 14 25" src="https://user-images.githubusercontent.com/26525777/53288362-cad6ea00-377e-11e9-8de6-74f64bb41201.png">

##  🚧  63
Name - **Bits**
👨‍💻- @kjhx 

<img width="1680" alt="screenshot 2019-02-23 at 15 14 01" src="https://user-images.githubusercontent.com/26525777/53288363-cad6ea00-377e-11e9-9601-9866544c984e.png">

## 🚧64
Name - **Water Drops** (suggested by @NSMyself)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 13 54" src="https://user-images.githubusercontent.com/26525777/53288364-cb6f8080-377e-11e9-8d58-49f7002b26f9.png">

## ✅ 65
Name - **Cubic Mess**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 13 46" src="https://user-images.githubusercontent.com/26525777/53288365-cb6f8080-377e-11e9-840b-a59903d3d398.png">

## ✅ 66
Name - **Neon**
👨‍💻-  @pedrommcarrasco 

![screenshot 2019-02-23 at 15 12 46](https://user-images.githubusercontent.com/26525777/53288366-cb6f8080-377e-11e9-8ae1-75a0f4355e3d.png)

## 🚧 67
Name - **Eggsy**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 20 25" src="https://user-images.githubusercontent.com/26525777/53288367-cb6f8080-377e-11e9-8a2a-052320d09a4a.png">

## 🚧 68
Name - **Cells** (suggested by @peusebio)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 19 50" src="https://user-images.githubusercontent.com/26525777/53288368-cb6f8080-377e-11e9-8d6b-533cb0c62d1c.png">

## 🚧 69
Name - **Watercolors** (suggested by @pedrommcarrasco )
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 19 03" src="https://user-images.githubusercontent.com/26525777/53288369-cc081700-377e-11e9-9eb0-6fc604a1e6b6.png">

## ✅ 70
Name - **Paintbrush** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 18 30" src="https://user-images.githubusercontent.com/26525777/53288370-cc081700-377e-11e9-8192-71085a001b0e.png">

## 🚧 71
Name - _Undefined_
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 17 48" src="https://user-images.githubusercontent.com/26525777/53288371-cc081700-377e-11e9-984a-e84d0ea8a36d.png">

##  🚧 72
Name - **Connectivity**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 17 13" src="https://user-images.githubusercontent.com/26525777/53288372-cc081700-377e-11e9-968a-61d802ac057b.png">

## 🚧  73
Name - **Fading Pieces**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 16 41" src="https://user-images.githubusercontent.com/26525777/53288373-cc081700-377e-11e9-8107-f1237693ea44.png">

## ✅  74
Name - **Monochrome**
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 52" src="https://user-images.githubusercontent.com/26525777/53288374-cc081700-377e-11e9-8a16-1275cda46bc8.png">

## ✅ 75
Name - **Lines** (suggested by @NSMyself)
👨‍💻-  @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 15 19" src="https://user-images.githubusercontent.com/26525777/53288375-cca0ad80-377e-11e9-8530-5d4f71e40b7b.png">

## ✅ 76
Name - **Virus** (suggested by @NSMyself)
👨‍💻- @pedrommcarrasco 

<img width="1680" alt="screenshot 2019-02-23 at 15 14 33" src="https://user-images.githubusercontent.com/26525777/53288376-cca0ad80-377e-11e9-9b01-86a226546003.png">

## ✅  77
Name - **Unstable Pipes**
👨‍💻-  @pedrommcarrasco 

![screenshot 2019-02-23 at 15 12 31](https://user-images.githubusercontent.com/26525777/53288377-cca0ad80-377e-11e9-9e36-2c8e6f17824b.png)

**Comment by MattSHallatt** [comment]
How's progress on this looking @pedrommcarrasco? I'm eager to add features once this separation has happened!

**Comment by pedrommcarrasco** [comment]
@MattSHallatt Not having much time, I'll probably just commit & push the ones I've already isolated so anyone can start doing things 😄

**Comment by MattSHallatt** [comment]
Sounds like a plan! I imagine it's not a particularly quick/easy job to separate them.

**Comment by pedrommcarrasco** [comment]
It's not hard really, if you ever used Adobe Premiere it's pretty straightforward except for some animations where it's harder to find a loop point but overall it's just time consuming

**Comment by kjhx** [comment]
Do you need any help isolating animations @pedrommcarrasco?

**Comment by pedrommcarrasco** [comment]
Extra hands are always welcome @kjhx 😄 
The goal is to extract every animation and create ~5secs loops that can be also be looped. This means you can replay a file smoothly.

I already did that for some, if you look inside the Resources folder, you'll see 
- `cubicMess.mp4`
- `neon.mp4`
- `runningInGrass.mp4`
- `unstablePipes.mp4`, this one is a bit longer because of the animation

As a guide of how I've been doing this, I've downloaded Apple presentation from iTunes and then I isolate and edit it in Adobe Premiere or Adobe After Effects. It's not hard at all, it's just time-consuming 😅
Unfortunately, I don't have the time needed for this since I'm currently working on another project during my free-time.
If you still want to help and/or need anything, please let me know. if you prefer to talk in private, you can DM me on twitter - https://twitter.com/pedrommcarrasco

**Comment by kjhx** [comment]
Alright, I'll start working on it in my free time. Cheers from /r/apple!

**Comment by pedrommcarrasco** [comment]
Great @kjhx! Much appreciated!
Whenever you have a new animation isolated, just open a PR with it 🙌

**Comment by pedrommcarrasco** [comment]
Hey guys, I update this issue with a list of animations. Feel free to suggest names and/or isolate animations. Just reply here :)

**Comment by peusebio** [comment]
.5 Gummy worms
.13 Shapes
.25 Stripes
.27 Layers
.29 Slices
.35 Iris
.40 Zebra
.41 Smoke/Smoking
.42 Picasso
.50 Windy
.53 Piano
.54 Bubbles
.68 Cells

@pedrommcarrasco just some thoughts! 😄

**Comment by NSMyself** [comment]
Just some ideas:

2 - Hills
26 - Play-doh
36 - Shelves and lightbubs
39 - City life
48 - Shards
38 - Volumetric 
50 - Blown away
51 - Leaf
56 - Glow
59 - Defragmentation
64 - Water drops
69 - Swirl
75 - Lines
76 - Virus
