### ISSUE TITLE
Random Order & Repeat Each Animation preferences do not work when on All Animations

### ISSUE THREAD

**Issue by lexnasser** [pedrommcarrasco/Brooklyn#30]
#### General troubleshooting

Before logging an issue please verify that:
- [x] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [x] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro 15" 2018 
- [x] macOS version: Mojave 10.14.3

#### Description of issue

Random Order & Repeat Each Animation preferences do not update the actual screensaver (same order and no repeat) when on All Animations

**Comment by pedrommcarrasco** [comment]
Do you have more than one item selected @lexnasser? If you only have "All Animations (Apple's Original Version" it's not going to work because that's not how it works.
