### ISSUE TITLE
You can‘t use Brooklyn with your current MacOS version

### ISSUE THREAD

**Issue by iDjay** [pedrommcarrasco/Brooklyn#32]
After downloading the latest version (2.0.1) it says that I can‘t use Brooklyn with my current MacOS (10.14.3 18D109). It worked fine with version 2.0.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pedrommcarrasco** [comment]
Take a look at #10 and see if it helps

>It's suggested that you download the file with Safari)
>And try everything with settings Closed from the start

**Comment by iDjay** [comment]
Yes for some reason re-installing fixed the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pedrommcarrasco** [comment]
MacOS is a bit tricky and really sensitive when it comes to screen savers 😅
