### ISSUE TITLE
Incompatible with os version

### ISSUE THREAD

**Issue by radesgn** [pedrommcarrasco/Brooklyn#33]
After few days install apear problem with compatibility of last mac os version.

**Comment by tgaul** [comment]
I had this same problem after installing 2.0 via Homebrew. I tried `brew upgrade brooklyn`, and there wasn't a new version (2.0.1) available there at the time, but I manually installed 2.0.1 from the download link and now it's working again.

**Comment by pedrommcarrasco** [comment]
Please, not trying to be rude but take a look at previous issues before opening a new one.
Take a look at #10 and see if it helps

> It's suggested that you download the file with Safari
> Try everything with settings Closed from the start

What changed from 2.0.0 to 2.0.1 shouldn't cause this except if your macOS is below 10.11 (10.9 and 10.10 were dropped)
