### ISSUE TITLE
Pixelated on 4K Monitor

### ISSUE THREAD

**Issue by sovon** [pedrommcarrasco/Brooklyn#34]
It's crisp & sharp on my 13" 2017 Macbook pro. But on external 4K monitor connected via USB-C, it looks pixelated and not very sharp. Any possible solution?

**Comment by pedrommcarrasco** [comment]
The original source is 1080p and depending in your resolution it may try to _"upscale"_.
I'll try to lock it down to its original resolution instead of scaling and fill the rest with the same background color.

Thanks for your report 👍

**Comment by sovon** [comment]
I tried to simulate how that would look. It looks way too small in 4K and 5K monitor. It would look worse.

**Comment by pedrommcarrasco** [comment]
Oh great to know! Thanks for trying!
I guess there's not much I can do then 😞

**Comment by sovon** [comment]
Is is possible for you to add this minimal clock (optional) to the screen saver?

![img](https://i.imgur.com/fi7PSmy.png)
![Imgur](https://i.imgur.com/L9hhGbF.png)
![Imgur](https://i.imgur.com/FpfVw6D.png)
![Imgur](https://i.imgur.com/G3eRHad.png)

**Comment by pedrommcarrasco** [comment]
That looks awesome @sovon! 😍
Did you design it?
Anyway please post it [here](https://github.com/pedrommcarrasco/Brooklyn/issues/6) 🙇‍♂️
If it's possible? Yes, for sure! The hardest part would be the gradient changing for every animation but as an MVP it could be light grey.

**Comment by sovon** [comment]
Yeah I designed it.
I'll post those in the other issue. With details.

**Comment by jeroen-meijer** [comment]
I ran an AI upscaler on the original animations (`Resources/original.mp4`) and I think the result was pretty good, although not perfect.

For anybody interested, you can [download it here](https://www.dropbox.com/s/gnc7hiq1u7vyia2/original.mp4.zip?dl=1).

Go to `~/Library/Screen Savers/Brooklyn.saver/Contents/Resources/`, rename `original.mp4` to something like `original_backup.mp4` and put the mp4 from the downloaded zip inside that folder.

Tada, 4K glory. 🎉

**Comment by pedrommcarrasco** [comment]
> I ran an AI upscaler on the original animations (`Resources/original.mp4`) and I think the result was pretty good, although not perfect.
> 
> For anybody interested, you can [download it here](https://www.dropbox.com/s/gnc7hiq1u7vyia2/original.mp4.zip?dl=1).
> 
> Go to `~/Library/Screen Savers/Brooklyn.saver/Contents/Resources/`, rename `original.mp4` to something like `original_backup.mp4` and put the mp4 from the downloaded zip inside that folder.
> 
> Tada, 4K glory. 🎉

Woah, that's pretty awesome! Thanks @jeroen-meijer!

**Comment by jeroen-meijer** [comment]
You're welcome!

Any chance this can be included in the repo?
It's quite a large video. I don't know if brew allows for install args but if it does, you could add some sort of argument during install, like `brew install brooklyn --include-4k`.

**Comment by pedrommcarrasco** [comment]
> Any chance this can be included in the repo?
Sure, and we don't even need brew, just your link and explaining how to do so would be enough for starters.

Brew would be a great option but I'm not very familiar with it nor I have the time to do so right now :/

**Comment by jeroen-meijer** [comment]
Cool. 😁

If I find the time I can try to make a PR that adds a little `sh` tool to the repo that can download and install the 4K version automatically. Does that sound good?

**Comment by pvanb** [comment]
> I ran an AI upscaler on the original animations (`Resources/original.mp4`) and I think the result was pretty good, although not perfect.

Curious what you used for this?

**Comment by jeroen-meijer** [comment]
@pvanb 

I used Topazlabs' Video Enhancer AI (free trial 😄).
https://topazlabs.com/video-enhance-ai/
