### ISSUE TITLE
"You cannot use this screen saver with this version of macOS"

### ISSUE THREAD

**Issue by jasonparmar** [pedrommcarrasco/Brooklyn#35]
"You cannot use this screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver" is what comes up now.
I'm running Version 10.13.6 - High Sierra

**Comment by pedrommcarrasco** [comment]
Did it use to work before or trying it out now?

Anyway, take a look at #10 and see if it helps

> It's suggested that you download the file with Safari
> Try everything with settings Closed from the start

MacOS is a bit tricky and really sensitive when it comes to screen savers written in Swift 😅

**Comment by jasonparmar** [comment]
Thanks!
I saw there were a few threads after I posted so I re-installed with system preferences closed and it worked!
I downloaded using Cliqz (built on Firefox) but it worked. Just kinda bizarre, ha!

Enjoying it now!

**Comment by pedrommcarrasco** [comment]
Glad it works! Thanks 🙇
