### ISSUE TITLE
Display current version

### ISSUE THREAD

**Issue by tkrajacic** [pedrommcarrasco/Brooklyn#37]
### Is your feature request related to a problem? Please describe.
I was looking for updates and now I am not sure if I have the latest version installed.

###  Describe the solution you'd like
It would be great if the screensaver pane would display the currently installed version number.

### Describe alternatives you've considered (Optional)
N/A

### Additional context
N/A

**Comment by pedrommcarrasco** [comment]
Hello @tkrajacic & welcome here! 😄 
That was supposed to exist when the preference panel released but I just forgot it completely, I'm sorry.
I'll add that in the next update, thanks. 🙇
