### ISSUE TITLE
Add a play-back option

### ISSUE THREAD

**Issue by p-z-l** [pedrommcarrasco/Brooklyn#39]
**Brooklyn will automatically play back an animation after it finishes, the feature works for most animations.  but for the rest, it may appears a little bit stiff.**

I wonder if you could add a play back option in screen saver settings?

**Comment by pedrommcarrasco** [comment]
What do you mean with stiff?

**Comment by p-z-l** [comment]
well i mean, for some animations, play-back function would become tricky.
anyway its not a software problem

for example:
playback looks fantastic with "Ball Pit".  while it fits bad with "Fruit Ninja"

**Comment by pedrommcarrasco** [comment]
Yes, that's a "design" issue
