### ISSUE TITLE
Provide a preferences menu to select which animations will be displayed

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/Brooklyn#4]
Provide a preferences menu to allow the user to select some preferences like:
* Which animations should be displayed
* etc ...

**I'm open to suggestions**

Only start implementing after #3 is solved

**Comment by pedrommcarrasco** [comment]
What a great idea @MattSHallatt 😮 
I'm still working on isolating and creating perfect loops of each animation but once that's done, it should be "easy" to catalog each one with tags.

Once they are isolated and pushed here, I will ping you here to see if you want to help dividing them by "tags"

**Comment by MattSHallatt** [comment]
Sounds good to me! Happy to help!

**Comment by amiantos** [comment]
Re: https://github.com/pedrommcarrasco/Brooklyn/issues/12#issuecomment-436996635

Maybe a better option would be to select how many times each loop should play, 1 time, 2 times, 3, etc. That's probably a better idea than "make it play longer".

**Comment by vipuldelwadia** [comment]
What about an option to randomize the order of animations?

**Comment by pedrommcarrasco** [comment]
Hey @vipuldelwadia & @amiantos 👋 
The features you requested are in the pull-request https://github.com/pedrommcarrasco/Brooklyn/pull/25, would be cool to have some feedback 😄

**Comment by amiantos** [comment]
@pedrommcarrasco Looks good to me! I haven't pulled it down and built it yet, but the screenshot looks nice.

**Comment by vipuldelwadia** [comment]
@pedrommcarrasco Yeah I don't have a good way to test out PRs (looks like Travis doesn't generate build artifacts for PR builds? 😞) but the screenshot is 👌

**Comment by pedrommcarrasco** [comment]
Thanks guys 🙇
