### ISSUE TITLE
Can't modify configuration

### ISSUE THREAD

**Issue by occupy5** [pedrommcarrasco/Brooklyn#40]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Macbook 2016
- [x] macOS version: Mojave 10.14
#### Description of issue
First of all, the screensaver works fine by `brew cask install brooklyn`. But I couldn't do some custom configuration since the button can't be clicked. Plus, I tried to use `brew cask upgrade brooklyn` but still didn't find a new version.
#### SnapShot
<img width="610" alt="Xnip2019-05-02_00-30-25" src="https://user-images.githubusercontent.com/16299493/57030907-cba56400-6c78-11e9-9a52-3deb15b289c2.png">

<img width="587" alt="Xnip2019-05-02_00-32-38" src="https://user-images.githubusercontent.com/16299493/57030920-d3650880-6c78-11e9-8a1f-e65fb46d59d8.png">

**Comment by pedrommcarrasco** [comment]
Brooklyn 1.0.0 didn’t support any custom configuration. That was added in the latest version 2.0.1

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/brooklyn.rb

**Comment by occupy5** [comment]
Thank you for your reply so fast, not support `brew cask ` to upgrade the version? (in my second snapshot)

**Comment by pedrommcarrasco** [comment]
It should be supported as you can see it in the URL I've sent you

**Comment by occupy5** [comment]
The reason I can't upgrade the version is that the problem of **git proxy**(it causes the brew to fail to update), now I have solved it. Thank you for your replies, I love brooklyn.

**Comment by pedrommcarrasco** [comment]
Happy you found out why @occupy5 🎉
