### ISSUE TITLE
I get all animations instead of selected ones

### ISSUE THREAD

**Issue by tarikkavaz** [pedrommcarrasco/Brooklyn#41]
#### General troubleshooting

Before logging an issue please verify that:
- [x] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [x] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: Mac Pro (Late 2013)
- [X] macOS version: Mojaev 10.14.4

#### Description of issue

Hi All, 
Even though I have selected just a few animations, I get all of them running. 
Do I miss something? 

![Screen Shot 2019-05-06 at 16 36 07](https://user-images.githubusercontent.com/5513457/57228732-30681200-701d-11e9-88d8-faa72fe701f6.png)

**Comment by pedrommcarrasco** [comment]
Hello @tarikkavaz,
This shouldn't be the case. Although, you have selected `Apple's Original Version` which will play the original animation that contains every single existing animation not-edited

**Comment by tarikkavaz** [comment]
> You current issue might be because you have selected `Apple's Original Version` which will play the original animation that contains every single existing animation not-edited

That's it.
I didn't realize that the `Apple's Original Version` would play all of them. 
Thanks.

**Comment by pedrommcarrasco** [comment]
No problem @tarikkavaz, enjoy it 😄
