### ISSUE TITLE
Select all options button

### ISSUE THREAD

**Issue by ppamorim** [pedrommcarrasco/Brooklyn#42]
### Is your feature request related to a problem? Please describe.
Hi, I would like to implement a button to auto select all items from the list. So I can easily unselect the ones I don't like for example.

###  Describe the solution you'd like
Maybe add a "select all" button below the table view or we can add a multi select function like this:

<img width="428" alt="Screenshot 2019-05-06 at 21 40 55" src="https://user-images.githubusercontent.com/5521682/57253877-b7ca7b00-7047-11e9-81aa-78d302c0e79e.png">

Multi select items and enable all of them if there is at least a deactivated item or disable all of them if they are all enabled.

**Comment by pedrommcarrasco** [comment]
You should be able to do that by selecting which ones you want and then pressing `space`
