### ISSUE TITLE
Unsupported on  Mojave 10.14.4

### ISSUE THREAD

**Issue by ApolloRisky** [pedrommcarrasco/Brooklyn#43]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Macbook Pro (Retina, 13-inch, Early 2015)
- [ ] macOS version: Mojave 10.14.4

#### Description of issue
![Screen Shot 2019-05-13 at 11 07 46 PM](https://user-images.githubusercontent.com/18187332/57637143-dba43880-75d4-11e9-9956-5a7df1912ef0.png)

**Comment by pedrommcarrasco** [comment]
Currently using it on 10.14.4 and it's working.
Anyway, take a look at #10 and see if it helps

> It's suggested that you download the file with Safari
> Try everything with settings Closed from the start
MacOS is a bit tricky and really sensitive when it comes to screen savers written in Swift 😅

**Comment by pedrommcarrasco** [comment]
Closing this since there wasn't an answer or feedback.
