### ISSUE TITLE
Unsupported 2-screens on mac OS 10.15Beta

### ISSUE THREAD

**Issue by keycheung** [pedrommcarrasco/Brooklyn#47]
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:  MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)  / DELL P2719H
- [x] macOS version:  10.15bate

#### Description of issue
couldn't support 2-screens on mac OS 10.15beta

**Comment by pedrommcarrasco** [comment]
Hm, interesting 🤔 
Unfortunately, I'm not able to install the beta on my main MacBook until I release the product I'm working on. I'll see what I can do 👍

**Comment by ccamaisa** [comment]
I'm on MacOS 10.15 Beta 1 (MacBook Pro 2016 w/ Touch Bar + 2.9G i5, 8G RAM) and it's only working for the built in display. My external HDMI display is just black.

**Comment by pedrommcarrasco** [comment]
Thanks for your report @ccamaisa.
Let's wait a bit until new versions drops since it's only a beta. (+ I can't install it on my main MacBook just yet)
