### ISSUE TITLE
Want to add more videos 

### ISSUE THREAD

**Issue by chintan9** [pedrommcarrasco/Brooklyn#48]
### Is your feature request related to a problem? Please describe.
I want add or remove video for screensaver. 

###  Describe the solution you'd like
Can you explain how should I add more video and build customized Brooklyn

### Describe alternatives you've considered (Optional)
none

### Additional context
Video requirement to add video.  

I am willing to build my own Brooklyn if has to that way to get thing done.

**Comment by pedrommcarrasco** [comment]
Could you provide some examples? Not quite sure of what you want or how that fits Brooklyn

**Comment by chintan9** [comment]
I want add my own videos for this app how can I do it.

**Comment by pedrommcarrasco** [comment]
That's still not very clear, which videos are we talking about?

**Comment by gamemasta0** [comment]
If I understand correctly, I think they want to use this as a general purpose video screensaver. It is not that, it’s meant to be just the animations from the Brooklyn event. If they want to add their own videos, they should make a fork and replace the video files in the project’s directory and the code that accesses them.

**Comment by pedrommcarrasco** [comment]
That’s what I’m trying to understand @gamemasta0. But answering both:
- if you want a general purpose screensaver, Brooklyn isn’t that, so you’ll have to build your own 
- if you want to add a new Apple animation, you’ll have to show it here to see if everybody agrees that it should be included. Then you would have to add it to the animations folder and create a case in the animations enum

**Comment by chintan9** [comment]
@pedrommcarrasco thanks for reply. 
@pedrommcarrasco thanks for clarify for situation.   

I will fork that and replace video file to code can access it

**Comment by pedrommcarrasco** [comment]
You welcome @chintan9, sorry for anything and good luck!
