### ISSUE TITLE
Can't execute under macOS Catalina dev beta 2 (10.15 beta (19A487l))

### ISSUE THREAD

**Issue by RuiCarneiro** [pedrommcarrasco/Brooklyn#49]
Says it "doesn't come from an identified programmer".

**Comment by deolarte** [comment]
I can confirm, cannot open even after approving. :(

**Comment by pedrommcarrasco** [comment]
Hey, sorry to hear but as I said in https://github.com/pedrommcarrasco/Brooklyn/issues/47
> "Unfortunately, I'm not able to install the beta on my main MacBook until I release a product I'm working on."

Would be great if anyone could give it a try

**Comment by Mheaus** [comment]
I succeeded when allowing it in the security menu after trying to launch the preview in the screensaver selector menu.
Now it's working, but only on my second ( and larger ) screen.

**Comment by jonliu03** [comment]
For you guys still wondering, disable System Integrity Protection. Then install it using Homebrew via terminal. Then, reenable SIP. Works like a charm!

**Comment by vipadm** [comment]
Can't execute under macOS Catalina public beta 2 (10.15 Beta (19A512f))

**Comment by ipv6freely** [comment]
Works fine in Catalina. No need to disable SIP. Just right click and select open, rather than double-clicking. That will give you the option to open it anyway.

**Comment by RuiCarneiro** [comment]
> Works fine in Catalina. No need to disable SIP. Just right click and select open, rather than double-clicking. That will give you the option to open it anyway.

This solution solves the problem also for Big Sur.
