### ISSUE TITLE
Homebrew cask support 

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/Brooklyn#5]
Homebrew cask will allow Brooklyn to be:
* installed via terminal
* receive automatic updates
* etc

**Comment by ygini** [comment]
If you support Homebrew, please also support MacPorts. Homebrew is full of weaknesses and can't be used for mass deployment scenario.

**Comment by pedrommcarrasco** [comment]
Sounds good to me @ygini, do you want to add that feature?

**Comment by ygini** [comment]
If only I had the time to do it… I just try to educates people too exposed to Homebrew that the solution isn't scalable and will not fit in an enterprise deployment, unlike MacPorts.

So depending of your goals, MacPorts will offer you a better coverage and will help ITs to deploy your payload correctly.

Which could be a nice things regarding your screensaver :)

**Comment by pedrommcarrasco** [comment]
Thanks for your feedback 😄

**Comment by Braden1996** [comment]
This seems to already be done? https://github.com/Homebrew/homebrew-cask/blob/e0d756cc99e7c49fae499d05653b527f59eae00c/Casks/brooklyn.rb

**Comment by pedrommcarrasco** [comment]
Great @Braden1996! Sadly, the author didn't inform me 😢 
Could you please test it and if everything is fine update Brooklyn's `README.md` to include this option?

**Comment by tarpdalton** [comment]
I just ran it (`brew cask install brooklyn`) and it's working fine

**Comment by pedrommcarrasco** [comment]
Can confirm! Thanks a lot @Braden1996  & @tarpdalton! 🙌 ❤️

**Comment by pedrommcarrasco** [comment]
Solved in https://github.com/pedrommcarrasco/Brooklyn/pull/24. Thanks a lot to both @Braden1996  & @tarpdalton 🙌
