### ISSUE TITLE
not possible to play only one animation

### ISSUE THREAD

**Issue by michelgin** [pedrommcarrasco/Brooklyn#53]
#### General troubleshooting

Before logging an issue please verify that:
- [ x] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [ x] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ iMac] Mac model:
- [ 10.14.6] macOS version: 

#### Description of issue

{{ not possible to play only one animation }}

**Comment by pedrommcarrasco** [comment]
I'm able to do it so it should be. Which animation are you trying to play @michelgin?

**Comment by ipv6freely** [comment]
If I understand the problem, then I'm having the same issue. I only have "Apple's Original Version" checked, and yet every animation plays. Catalina 19A536g.

**Comment by pedrommcarrasco** [comment]
@ipv6freely "Apple's Original Version" means every single animation without any modification
