### ISSUE TITLE
Resolution and speed

### ISSUE THREAD

**Issue by triplec76** [pedrommcarrasco/Brooklyn#55]
Is the resolution of the latest version worse than previous versions? Especially on "Apple's Original Version" it is noticeably pixelated. I don't recall that on a previous build I was running. As a matter of fact, it looked beautiful before.

Also, I would love to have an option to slow the animation down a bit, in addition to the number of replays already added.

Thank you for your work!

**Comment by pedrommcarrasco** [comment]
As far as I remember nothing changed regarding that 🤔 
I'm afraid that's not possible since we're dealing with 29fps footage 😞

**Comment by triplec76** [comment]
Ok! Very possible it's something on my end. I'll look into it. Thank you again for this great work.

**Comment by drvain** [comment]
I apologize if this isn’t the correct route for asking this question, I’m still a noob with developing and finding my way around… First I have to say I love the screensaver, love seeing the different interpretations of the logo! My question is, is there a way to make this into a video wallpaper for the desktop? I know there are some avenues with VLC or terminal but is there something I haven’t seen or a trick I might be missing? If I need to ask this question elsewhere, please let me know. But if there is something already put together along that line, I would love to implement it.

Again, thanks for the amazing work.

M.

**Comment by pedrommcarrasco** [comment]
Thanks for the kind words @triplec76 🙌 
Regarding your question @drvain, you mean using Brooklyn as a desktop wallpaper? I have no idea if that's even possible but if it's it will probably be a little _hacky_
