### ISSUE TITLE
Add Sparkle for automatic updates

### ISSUE THREAD

**Issue by pedrommcarrasco** [pedrommcarrasco/Brooklyn#56]
Right now, Brooklyn needs to be updated manually or via homebrew. This may lead to people not using the latest version and missing some new features.
[Sparkle](https://github.com/sparkle-project/Sparkle) is a well know framework that solves this. In the end, this would improve the UX of Brooklyn and increase the number of people using the latest version.

**Comment by nehayward** [comment]
Do you still need help with this?

**Comment by pedrommcarrasco** [comment]
Could use an hand here @nehayward 👍

**Comment by nehayward** [comment]
Great I'll get started. It looks like you don't have any dependencies right now, I'm leaning towards just added in the framework manually, so we don't have to introduce cocoa pods.

**Comment by nehayward** [comment]
Any ideas on where you'd like to host the feed url?

https://sparkle-project.org/documentation/

**Comment by pedrommcarrasco** [comment]
We can host it on my personal page @nehayward. Can you send me the file and I will send you a link or do you want me to handle it?

**Comment by nehayward** [comment]
The file is too big to add to Github. Here is a [link](https://we.tl/t-VCr1YA6JTY)

**Comment by nehayward** [comment]
I'll probably need to gen this again, once you know the URL path it'll be hosted at.

**Comment by nehayward** [comment]
Correct, so the SUFeedURL = "https://pedrommcarrasco.github.io/projects/brooklyn/update" maybe?

**Comment by pedrommcarrasco** [comment]
https://pedrommcarrasco.github.io/projects/brooklyn/ should be enough. But you have to send the XML first so I can upload it no?

**Comment by nehayward** [comment]
Oh we might be able to link to the GitHub source of the zip file actually

**Comment by nehayward** [comment]
```
<?xml version="1.0" standalone="yes"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
    <channel>
        <title>Brooklyn</title>
        <item>
            <title>2.1.0</title>
            <pubDate>Tue, 29 Oct 2019 09:07:08 -0700</pubDate>
            <sparkle:minimumSystemVersion>10.11</sparkle:minimumSystemVersion>
            <enclosure url="https://github.com/pedrommcarrasco/Brooklyn/releases/download/2.0.1/Brooklyn.saver.zip" sparkle:version="3" sparkle:shortVersionString="2.1.0" length="216674805" type="application/octet-stream"/>
        </item>
    </channel>
</rss>
```

**Comment by nehayward** [comment]
With the URL being 2.1.0

**Comment by pedrommcarrasco** [comment]
This would mean we would have to update the URL every time we make a new release right?

**Comment by nehayward** [comment]
Yes I think with every update you add a new item to the channel with the update version number so the next would be this

```
<?xml version="1.0" standalone="yes"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
    <channel>
        <title>Brooklyn</title>
        <item>
            <title>2.2.0</title>
            <pubDate>Tue, 29 Oct 2019 09:10:08 -0700</pubDate>
            <sparkle:minimumSystemVersion>10.11</sparkle:minimumSystemVersion>
            <enclosure url="https://github.com/pedrommcarrasco/Brooklyn/releases/download/2.2.0/Brooklyn.saver.zip" sparkle:version="3" sparkle:shortVersionString="2.2.0" length="216674805" type="application/octet-stream"/>
        </item>
        <title>Brooklyn</title>
        <item>
            <title>2.1.0</title>
            <pubDate>Tue, 29 Oct 2019 09:07:08 -0700</pubDate>
            <sparkle:minimumSystemVersion>10.11</sparkle:minimumSystemVersion>
            <enclosure url="https://github.com/pedrommcarrasco/Brooklyn/releases/download/2.0.1/Brooklyn.saver.zip" sparkle:version="3" sparkle:shortVersionString="2.1.0" length="216674805" type="application/octet-stream"/>
        </item>
    </channel>
</rss>
```

**Comment by pedrommcarrasco** [comment]
In the meantime, I had a better idea for hosting the appcast.xml.
Here it is: https://github.com/pedrommcarrasco/Brooklyn/blob/master/appcast.xml

**Comment by nehayward** [comment]
Okay yeah that works good too.

**Comment by nehayward** [comment]
Yeah I agree

**Comment by pedrommcarrasco** [comment]
Done ✅ 
Is it alright?

**Comment by pedrommcarrasco** [comment]
I was wondering the same :D

**Comment by pedrommcarrasco** [comment]
Maybe we should start on 2.0.1 🤔

**Comment by pedrommcarrasco** [comment]
If it works there, it would work on 2.1.0 (I hope 😂)

**Comment by pedrommcarrasco** [comment]
What do you think?

**Comment by nehayward** [comment]
I'm okay with that :)

**Comment by pedrommcarrasco** [comment]
Updated `appcast.xml` to 2.0.1

**Comment by nehayward** [comment]
Hmm 🤔 I updated the SUFeedURL but it fails to load still. I update the PR if you want to take a look. I'm still trying to debug it.

**Comment by pedrommcarrasco** [comment]
Maybe because you're currently with version 2.1.0?

**Comment by nehayward** [comment]
Maybe I figured it should load the URL still. I took a look at Aerial to see how they implement it too.

https://github.com/JohnCoates/Aerial
