### ISSUE TITLE
Translation: Korean

### ISSUE THREAD

**Issue by miniesam** [pedrommcarrasco/Brooklyn#59]
Since I liked this project, I wanted to do something.
So I'd like to contribute by translating the documents of this project into Korean.
If it is okay, please let me know. :)

**Comment by pedrommcarrasco** [comment]
That sounds great, go for it!

**Comment by miniesam** [comment]
Hello, @pedrommcarrasco!
I'm happy to be able to translate this project. :)
First of all, I want to translate `README.md`.
Would you like to create a new file, such as `README_ko.md` and then translate the original into Korean at `README_ko.md`?

**Comment by pedrommcarrasco** [comment]
Perfect!

**Comment by miniesam** [comment]
Great news, @pedrommcarrasco!
I just finished translating and all I have to do is get ready to do Pull Request.
So, where should I save `README_ko.md` anyway?
I think the root directory of the repository is fine, but let me hear your opinion first.

**Comment by pedrommcarrasco** [comment]
That's great (and fast)! 🎉

> So, where should I save README_ko.md anyway?
I think the root directory of the repository is fine, but let me hear your opinion first.

Maybe we should have it inside a folder called translations or something similar? We should have something in the main README.md that links to it

**Comment by miniesam** [comment]
Sure, then how about making the `Translations` folder and make subdirectories like `en` or `ko`?
And save `README_ko.md` inside the `~/Translations/ko`.

**Comment by pedrommcarrasco** [comment]
Sounds good and future proof to me (in case we have more than 1 document to translate)
