### ISSUE TITLE
Inconsistent logo size

### ISSUE THREAD

**Issue by michaelbjacobson** [pedrommcarrasco/Brooklyn#66]
#### General troubleshooting

Before logging an issue please verify that:
- [✔️] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [✔️] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- Mac model: MacBook Pro, 13-inch, 2018, Four Thunderbolt 3 Ports, 2.7 GHz Quad-Core Intel Core i7
- macOS version: 10.15.1 (Catalina. Latest public version at time of posting)

#### Description of issue

Since upgrading to macOS Catalina, the screensaver occasionally (and seemingly at random) will render the Apple icon in the bottom-left corner of the screen, and only about an inch in size. The animations work correctly. I've uninstalled Brooklyn and re-installed using both Homebrew, and manual installation, but the issue persists.

Please see attached screenshot for illustration.

<img width="1440" alt="Screenshot 2019-11-13 at 13 37 44" src="https://user-images.githubusercontent.com/25020231/68768623-ceffac00-061a-11ea-99bd-b6a46e7a5780.png">

**Comment by leehord** [comment]
I think this may be limited to MacBook's that contain a discrete GPU. I have another MacBook I use which only has the integrated GPU and this issue never occurs there.

**Comment by pedrommcarrasco** [comment]
uhuh, this is a _cool_ one 🤔

**Comment by marility** [comment]
just right click and select open, rather than double-clicking. 
i fix the problem by follow the answer of @ipv6freely  in #49

**Comment by fletech** [comment]
I made this:
 As I downloaded the installer on Desktop, I've left it in there. Then I installed it but I saw this common issue when it began to run. So I moved it from Desktop towards its path, which is:
/Users/USERNAME/Library/Screen Savers.
I've fixed it like this.
Cheers!
