### ISSUE TITLE
New Animations?

### ISSUE THREAD

**Issue by pvanb** [pedrommcarrasco/Brooklyn#69]
There appear to be some new animations in Apple’s “[Join us. Be you.](https://www.apple.com/jobs/us/)” jobs promo video.

It would be great if they could be incorporated into the screensaver.

Direct link to video (not sure if a higher res version is available): https://www.apple.com/jobs/global/media/acvideo/2020-index/us/2020USHero-HD-cc-us-2020_1280x720.mp4

**Comment by pedrommcarrasco** [comment]
Really happy to see Apple using these animations again! 

I’ll look into it once I have time.

**Comment by MuathIbnHassan** [comment]
This is a FullHD version

https://www.apple.com/jobs/global/media/acvideo/2020-index/us/2020USHero-HD-cc-us-2020_1920x1080h.mp4

**Comment by anurag2pirad** [comment]
The new ones look sick!

**Comment by kcmannem** [comment]
would love this too

**Comment by yachtpressgang** [comment]
I just wish I could work out HOW to install as screensaver on my MacBook Pro. I am not as knowledgeable as you guys.

**Comment by pvanb** [comment]
Happy to see these made it in. Just wanted to mention that the download link in Readme.rd is still pointing to the old version.

**Comment by pedrommcarrasco** [comment]
Nicely spotted! Do you mind opening a PR with a fix?
