### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by seonline** [pedrommcarrasco/Brooklyn#70]
So after the update to macOS Catalina 10.15.3 the screensaver no longer plays and a message appears: You cannot use the Brooklyn screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver. I'm running Brooklyn 2. Is there another version?

**Comment by pedrommcarrasco** [comment]
I'm running macOS Catalina 10.15.3 here and it looks fine.
Please try reinstalling it.

**Comment by seonline** [comment]
I think it’s because I’m running dual screens. Which is weird because before the update it would work on both simultaneously. I unplugged one and now it works.

Scott Elliott
714.863.2130
