### ISSUE TITLE
Not working in MacOS 10.15.3

### ISSUE THREAD

**Issue by DineshAdhi** [pedrommcarrasco/Brooklyn#72]
Recently updated my MacBook Pro (15 inch, 2018) to MacOS 10.15.3. 

The message prompt says to contact developer because the screen saver does not work in this OS version.

**Comment by maxmatthews** [comment]
Follow the instructions in the read me to go to system preferences > security to allow it to run. https://github.com/pedrommcarrasco/Brooklyn#manual-hand

**Comment by pedrommcarrasco** [comment]
Thank you for taking care of this one @maxmatthews 👍
