### ISSUE TITLE
Longer times

### ISSUE THREAD

**Issue by boingfromdiscord** [pedrommcarrasco/Brooklyn#76]
### Is your feature request related to a problem? 
It bothers me that the screen savers last for such a short time. They are so good

###  Describe the solution you'd like
The screen saver you choose repeats until you wake up your Mac

**Comment by coltoneshaw** [comment]
Agreed! I would love to see the animations slowed down slightly to make them less rushed and fit a bit more with a traditional screensaver speed. Love this though!

**Comment by pedrommcarrasco** [comment]
There's no way to achieve this given that we don't own the animations - they were done by Apple.
By doing so, and since the animations are at 30 fps, they would lag and showcase the poor frame rate.

**Comment by coltoneshaw** [comment]
What about taking the file and looping it? The animations are fantastic it's just a bit fast to switch around.

**Comment by pedrommcarrasco** [comment]
You can do that already in the preferences menu for Brooklyn. Are you using the latest version @coltoneshaw?

**Comment by coltoneshaw** [comment]
I did not know that! I am not using the latest, I turned it off due to this a while back. Let me try it again!

**Comment by pedrommcarrasco** [comment]
Download the latest one and give it a shot, it has a bunch of animations and a few options that might help you find your sweet spot
