### ISSUE TITLE
Battery drain on Laptops

### ISSUE THREAD

**Issue by frbuccoliero** [pedrommcarrasco/Brooklyn#78]
Hi, i would like to know from MBPs and Hackintosh Laptop users how much does the Screensaver drain battery when not powered to AC. Thank you :D

**Comment by simplenotezy** [comment]
And possibly a feature to disable screensaver on battery! :)

**Comment by parion** [comment]
> And possibly a feature to disable screensaver on battery! :)

@simplenotezy what do you mean by "disable screensaver"? A black screen? If so, couldn't you configure Energy Saver preferences to turn the display off before the screensaver timeout?

**Comment by simplenotezy** [comment]
@parion good idea. Don't know if that is possible

**Comment by maelcum** [comment]
@simplenotezy Of course that is possible. Just check System Preferences > Energy Saver.
