### ISSUE TITLE
Animation Displayed Compactly in Corner

### ISSUE THREAD

**Issue by parion** [pedrommcarrasco/Brooklyn#79]
#### MacOS Info
- Mac model: 2020 13" MacBook Pro
- macOS version: 11.0 Beta (20A5364e)

#### Description of issue

_I understand this issue is occurring in a beta version of MacOS, thought I'd still bring attention to it in the event it carries over to the official release of Big Sur._

The screensaver displays the Brooklyn animation, but it's confined to the bottom left corner of the screen in a miniature view.

**Preview**:
<img width="1440" alt="Screen Shot 2020-09-13 at 11 59 15 AM" src="https://user-images.githubusercontent.com/4733032/93026260-98d3e580-f5b9-11ea-87d6-eb051495d0ee.png">

**Comment by fletech** [comment]
I made this: 
I moved the file Brooklyn.Saver from Desktop towards the right folder, its path is: /Users/USERNAME/Library/Screen Savers. I figured out like that. 

Cheers!

**Comment by sammosna** [comment]
@fletech for me it doesn't work anyway..

**Comment by Mosher23** [comment]
i am on mac OS 11 and its is same for me. little animation in left bottom corner

**Comment by parion** [comment]
Duplicate of #66 and #67.

**Comment by MBibal** [comment]
On my MacMini 2020 with BigSur public beta 2 it still runs on lower left corner
