### ISSUE TITLE
Slower animation?

### ISSUE THREAD

**Issue by TimAlberry** [pedrommcarrasco/Brooklyn#82]
Hi,

Love the app. Especially that a different logo animates on each of my muliple screens.

What would make the app perfect for me would be if we could slow down the animation. I don't know how that app works - but if it is easy to do, that would be very, very cool.

Tim

**Comment by yachtpressgang** [comment]
I agree, that would be great. At the moment it’s too fast take in the brilliant graphics. 

=========
With best wishes from
Barry Feldman 
ברוך בן יצחק משה

0044 (0)7798 833039
Should I not be available by telephone I can ALWAYS be contacted by email.

**Comment by winkelmant** [comment]
Edit these files:
/Users/<USER>/Library/Screen Savers/Brooklyn.saver/Contents/Resources

And you'll get what you want :)

**Comment by yachtpressgang** [comment]
I wish I knew how to do it. 

=========
With best wishes from
Barry Feldman 
ברוך בן יצחק משה

0044 (0)7798 833039
Should I not be available by telephone I can ALWAYS be contacted by email.

**Comment by TimAlberry** [comment]
Aha - I see, this screensaver is mp4 videos being played. For some mad reason I had assumed they were being "generated". 

So I could take mp4 files and slow them down and put them back in said location.

Thanks for showing me :)

Kind regards,

Tim

**Comment by pedrommcarrasco** [comment]
That's correct @TimAlberry.

The issue here is that these animations were "provided" by Apple at with a frame rate of 30 frames per second. This means that any attempt at slowing it down will look laggy.

You could try to convert it to 60 frames per second with the help of AI/software but that's unexplored territory for me.

**Comment by pedrommcarrasco** [comment]
You can also try to update to the latest version which will not make animations slower but will allow you to loop over specific animations before switching to a different one @TimAlberry
