### ISSUE TITLE
Not working in MacOS 11.0 M1 chip

### ISSUE THREAD

**Issue by Maxxamaxx** [pedrommcarrasco/Brooklyn#83]
My MacBook Air (13 inch, 2020 M1 chip) MacOS 11.0

The message prompt says
You cannot use the Brooklyn screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver.

**Comment by pedrommcarrasco** [comment]
This could be a generic error message, not directly related to the new M1 chip.
Please look into this [issue](https://github.com/pedrommcarrasco/Brooklyn/issues/10).

**Comment by Maxxamaxx** [comment]
It worked. Thanks @pedrommcarrasco
