### ISSUE TITLE
Brooklyn now longer works with Big Sur 11.2

### ISSUE THREAD

**Issue by BertNase** [pedrommcarrasco/Brooklyn#88]
Since 11.2 the screensaver can't be started. It says: Not working with this MacOS version. I should contact programmer...

**Comment by emmceemoore** [comment]
Just to add another data point, I'm on 11.2 and the screensaver continues to work fine for me. 🤷 

It may be helpful to whoever looks at this if you include some additional information about your setup (hardware, installation method, etc.).

**Comment by vasudevnair113** [comment]
Oh im on 10.15.7 Catalina and I got the same issue. I resolved it by going to security and allowing the file to open.

**Comment by BertNase** [comment]
> Oh im on 10.15.7 Catalina and I got the same issue. I resolved it by going to security and allowing the file to open.

you only get this message if you install it for all users. If you install it only for your account you don't have to explicitly allow it. At least with Big Sur 11.2.

**Comment by BertNase** [comment]
> Just to add another data point, I'm on 11.2 and the screensaver continues to work fine for me. 🤷
> 
> It may be helpful to whoever looks at this if you include some additional information about your setup (hardware, installation method, etc.).

Interesting. It's an iMac with Intel CPU. As I said, it worked since 11.01 until 11.1. I downloaded the latest brooklyn saver and it doesn't work neither. "This screensaver can't be used with this release of MacOS. Contact manufactorer to get a newer version". 11.2 was installed like 11.1 and the other Big Sur releases before.

**Comment by BertNase** [comment]
I removed the screensaver again (I had the later release copied over the old one), rebooted and installed again. Now it's working again. I love it! Thanks!
