### ISSUE TITLE
Animations seem to play, reverse, then move on

### ISSUE THREAD

**Issue by vasudevnair113** [pedrommcarrasco/Brooklyn#89]
Hi guys, im using a iMac (21.5-inch, Late 2012) that is running macOS Catalina (10.15.7) and I noticed that the animations seem to reverse? It'll play the animation, then reverse, then move on to the next. Is that supposed to be happening? Because on the animation in the "read me" section, it seems to play once then move on to the next. It doesn't play, reverse, then move on. Any help would be appreciated. Thank you!

**Comment by pedrommcarrasco** [comment]
It depends on which animation you choose and how many times you want it to loop.

If you want to original version, simply select the first one and you won't see any reverse

**Comment by vasudevnair113** [comment]
Ah I see! It works now! Thank you, much appreciated! Love the screen saver :)
