### ISSUE TITLE
New bunch of apple logo design can be added

### ISSUE THREAD

**Issue by designedbyclu** [pedrommcarrasco/Brooklyn#90]
### Is your feature request related to a problem? Please describe.
Besides the Logos in current, i found there is bunch nice static Apple Logo could be added. 

###  Describe the solution you'd like
Create few transition animation for these apple logo.
https://drive.google.com/drive/folders/10axlbJx77MZutoATv-Homij3MwGoqPB2?usp=sharing

**Comment by nmcc1212** [comment]
imo, my favourite part of the project is the animation of the logos
