### ISSUE TITLE
Screen Saver can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by jcannon23** [pedrommcarrasco/Brooklyn#95]
#### General troubleshooting

Before logging an issue please verify that:
- [ ] You have the latest version installed at https://github.com/pedrommcarrasco/Brooklyn/releases
- [ ] Your issue isn't mentioned in our [issues](https://github.com/pedrommcarrasco/Brooklyn/issues). 

If none of this fixes your issue, tell us more about it.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 

#### Description of issue

After installing and following the directions to go into 'Security & Privacy' and then click 'Open Anyway' for the "Brooklyn.saver", I'm still receiving the error message “Brooklyn.saver” can’t be opened because Apple cannot check it for malicious software.
![Screen Shot 2021-05-25 at 7 54 38 AM](https://user-images.githubusercontent.com/23659754/119501476-81472200-bd2e-11eb-917e-4bd0cc2f7101.png)

**Comment by Azzuurro** [comment]
Same issue on my side but if you are following the followed steps, it should work!

1. Open Preferences
2. Select Security & Privacy
3. Select General
4. On the bottom side, select Open Anyway

Works on:
macOS Big Sur 11.4
MacBook Pro (2019)

**Comment by Onedah** [comment]
Im having same issue on MB Pro 16" with macOS Big Sur 11.5.2 appears that it needs to be updated.

**Comment by Yb-G** [comment]
@Onedah, use the steps that Azzuurro sent. It even works for my Macbook Air (2017) running 11.4 (20F71)!

Link: https://github.com/pedrommcarrasco/Brooklyn/issues/95#issuecomment-851346570

**Comment by Onedah** [comment]
@Yb-G tried the steps but does not work on MacOS 11.52

**Comment by AxelVincent** [comment]
You can bypass the click button solution by using this command to stop the apple macbook quarantine on the file in your terminal :

```shell
sudo xattr -d com.apple.quarantine ~/"Library/Screen Savers/Brooklyn.saver"
```

**Comment by Onedah** [comment]
> You can bypass the click button solution by using this command to stop the apple macbook quarantine on the file in your terminal :
> 
> ```shell
> sudo xattr -d com.apple.quarantine ~/"Library/Screen Savers/Brooklyn.saver"
> ```

Thanks the above worked.

**Comment by Yb-G** [comment]
@pedrommcarrasco, it would be better if you put the above command in a Troubleshooting section in the README.md file so it would help other people instead of finding for this issue! 😃

**Comment by pedrommcarrasco** [comment]
> @pedrommcarrasco, it would be better if you put the above command in a Troubleshooting section in the README.md file so it would help other people instead of finding for this issue! 😃

Sounds good to me, please open a Pull Request with your suggestion!
